### ISSUE TITLE
Pre-trained target classifiers

### ISSUE THREAD

**Issue by arlse** [LiulietLee/CDTA#1]
请问Pre-trained target classifiers里的模型具体是怎么训练的，可以提供下这部分代码吗？

**Comment by skydiver-jay** [comment]
同样的疑问，希望能够提供下这部分代码

**Comment by skydiver-jay** [comment]
> 请问Pre-trained target classifiers里的模型具体是怎么训练的，可以提供下这部分代码吗？

我猜你可能跟我遇到类似的疑问了。CDTA文章里关键的feature extractor训练相关代码在仓内cst路径下。 target classifiers只是攻击目标并不是由攻击者训练的。
